### PR TITLE
task_01 packages

### PR DESCRIPTION
**Pull request by ayine17**
@cheuschober

### CODE REVIEW

**Comment by cheuschober** [comment]
@ayine17, looks like a bad example line on my part. Should read,

    import task01.peanut

**Comment by smajid** [comment]
?

Professor,


I don't get it...is this message meant for us all?


I am having problems with this one, I followed your directions on warmup task01, but it's not working...is there a problem with the directions?

_____________________

Saulat Majid
571.291.5913
________________________________

**Comment by cheuschober** [comment]
@smajid, there's no problem with the directions -- just the example 
line. The second example was correct the first was missing a '.peanut'

**Comment by ayine17** [comment]
@cheuschober 
my code failed with this "ImportError: No module named task_03"  and i don't know what is the problem.

**Pull request merged**
