### PR TITLE
Week 6 Warmup's 

### PR DESCRIPTION
**Pull request by eliz79**
Week 6 Warmups.

### CODE REVIEW

**Comment by cheuschober** [comment]
@eliz79, Nice job passing the unit tests! Now just get those violations fixed!

**Comment by eliz79** [comment]
Professor, 
I'm not sure how to get rid of the violation, because the steps you said was to "import task_01"; although I don't see us using task_01.

The only way i can get rid of the violation is by not importing task_01.

**Comment by cheuschober** [comment]
@eliz79, Not importing task_01 was the right thing to do. It's not necessary inside the package.

**Comment by eliz79** [comment]
Awesome - i actually understood it lol

**Pull request merged**
